insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Exclusive 5th generation synergy', 'Vivamus tortor. Duis mattis egesmpor convallis.', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'https://i0.wp.com/www.dolphinmusic.co.uk/shop_image/uploads/Image/justice1.jpg', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Assimilated asynchronous adapter', 'Donnar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://cliqueimg.com/cache/posts/img/uploads/current/images/0/233/762/main.original.640x0c.jpg', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Adaptive coherent software', 'Morbi , nisl. Nunc rhoncus dui vel sem.', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://dummyimage.com/214x161.png/5fa2dd/ffffff', 1);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Implemented maximized initiative', 'Vivamus metus arcn felis eu sapien cursus vestibulum.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/210x246.png/ff4444/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Decentralized disintermediate intranet', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/143x190.png/5fa2dd/ffffff', 1);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Mandatory heuristic internet solution', 'Sed sagittis. Nam congue, risunt montes, nascetur ridiculus mus.', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/223x185.png/5fa2dd/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Stand-alone bandwidth-monitored throughput', 'Aliquam non mauoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/152x128.jpg/cc0000/ffffff', 1);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Cross-platform composite throughput', 'Morbi sem mauris, laenti. Cras in purus eu magna vulputate luctus.', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/192x148.jpg/5fa2dd/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Public-key full-range utilisation', 'Donec  leo. Pellentesque ultrices mattis odio.', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/233x207.bmp/cc0000/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Configurable modular help-desk', 'Fusce s vulputate elementum.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dummyimage.com/135x247.png/dddddd/000000', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Fundamental logistical concept', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.

Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/107x175.bmp/dddddd/000000', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Universal discrete product', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/213x197.bmp/5fa2dd/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Open-source methodical projection', 'Pellentesque at nulla.', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.

Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/199x103.png/ff4444/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Advanced secondary encryption', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/120x174.png/ff4444/ffffff', 1);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Realigned bandwidth-monitored throughput', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/236x168.png/cc0000/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Switchable transitional moderator', 'Donec semper sapien a libero. Nam dui.', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/172x191.png/cc0000/ffffff', 1);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Re-contextualized analyzing ability', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/234x130.png/cc0000/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Universal optimizing strategy', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.

Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'http://dummyimage.com/132x199.jpg/cc0000/ffffff', 1);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Assimilated even-keeled portal', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/102x132.bmp/cc0000/ffffff', 2);
insert into blog_posts (title, subtitle, content, image_url, artist_id) values ('Robust leading edge info-mediaries', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/206x207.jpg/cc0000/ffffff', 1);
